# -*- coding: utf-8 -*-
"""FP-Growth-2205-Baris-Transaksi-Project-Pribadi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgOIjyerp6aiAG4sakBl9Utam866UwSC
"""

# =================  Connecting To Google Drive  ================= #

from google.colab import drive
drive.mount('/content/drive')

# END

# =================  Libary  ================= #

import pandas as pd
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules

# END

# =================  Import Database  ================= #

# Membaca Database
db = pd.read_excel('/content/drive/MyDrive/Dataset_Training/ifood_df.xlsx')

# Menampilkan nama-nama kolom dalam dataset
print(db.columns)

# END

# =================  Langkah KDD Data Selection  ================= #

# Memilih Atribut (Data Selection)
selected_attributes = db[['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']]

print(selected_attributes)

# END

# =================  Langkah KDD Transformation  ================= #

# Mengubah nilai atribut sesuai kondisi
selected_attributes = selected_attributes.applymap(lambda x: 1 if x >= 1 else 0)

print(selected_attributes)

# END

# =================  Langkah KDD Data Mining (FP-Growth) ================= #

# Melakukan Analisis Frequent Itemsets Menggunakan FP-Growth (Data Mining)
frequent_itemsets = fpgrowth(selected_attributes, min_support=0.8, use_colnames=True)

# Mengurutkan frequent_itemsets berdasarkan kolom 'support' secara descending
frequent_itemsets_sorted = frequent_itemsets.sort_values(by='support', ascending=False)

#print("\nFrequent Itemsets:")
#print(frequent_itemsets_sorted)

# END

# =================  Langkah KDD Data Mining (Association Rules) ================= #

# Menampilkan Hasil Hubungan Asosiasi (Data Mining)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.9)

#print("\nAssociation Rules:")
#print(rules)

# END

# Menampilkan hanya kolom antecedents, consequents, support, dan confidence
selected_columns = rules[['antecedents', 'consequents', 'support', 'confidence']]

#print("\nAssociation Rules (Selected Columns):")
#print(selected_columns)

# =================  Langkah KDD Knowlegde ================= #

# Menggunakan fungsi association_rules untuk mendapatkan aturan asosiasi
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.9)

# Mengurutkan berdasarkan confidence secara descending
rules_sorted = rules.sort_values(by='confidence', ascending=False)

# Iterasi untuk mengubah setiap baris menjadi kalimat dengan nomor urut
for i, (index, row) in enumerate(rules_sorted.iterrows(), start=1):
    antecedents = list(row['antecedents'])
    consequents = list(row['consequents'])
    confidence = round(row['confidence'] * 100, 2)

    antecedents_str = ', '.join([str(elem) for elem in antecedents])
    consequents_str = ', '.join([str(elem) for elem in consequents])

    print(f"{i}. Jika item \"{antecedents_str}\" dibeli maka punya kemungkinan {confidence}% item \"{consequents_str}\" akan dibeli juga.")

    # END